server:
  port: 9005
  error.whitelabel.enabled: false
  servlet:
    session:
      timeout: 1800

spring:
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/tuleva-onboarding
    username: tuleva-onboarding
    password: tuleva-onboarding
    continue-on-error: false
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-on-borrow: true
      test-while-idle: true
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9000/oauth/check_token
    client:
      client-id: epis-service
      client-secret: epis-service

ssl:
  trustAllHTTPSHosts: true

truststore:
  path: "test_keys/truststore.jks"

mhub:
  host: a2atest1.nasdaqcsd.com
  port: 14152
  queueManager: NCSDBXT1
  channel: TULEVAP
  peerName: "CN=a2a-test-gw, O=Nasdaq CSD, C=LV"
  inboundQueue: BMMH.TULEVAP.OUT
  outboundQueue: BMMH.TULEVAP.IN
  keyStore: ${MHUB_KEYSTORE}
  keyStorePassword: ${MHUB_KEYSTORE_PASSWORD}
  userid: ${MHUB_USERID}
  password: ${MHUB_PASSWORD}

epis:
  service:
    url: http://localhost:9005/v1
    bic: "TULEVA20PPP"

---

server.port: 5000

spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    tomcat:
      max-active: 60
    initialization-mode: never
  rabbitmq:
    host: ${MQ_HOST}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtualHost: ${MQ_USERNAME}

security:
  oauth2:
    resource:
      token-info-uri: ${TOKEN_INFO_URI}
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

logging:
  rollbar:
    accessToken: ${ROLLBAR_ACCESS_TOKEN}

epis:
  service:
    url: https://epis-service.herokuapp.com/v1

mhub:
  host: a2a-gw1.nasdaqcsd.com
  queueManager: NCSDBXP1
  peerName: "CN=a2a-gw1.nasdaqcsd.com,OU=Domain Control Validated"
