server:
  port: 9005
  error.whitelabel.enabled: false
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 1800

spring:
  application:
    name: 'EPIS Service'
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    user:
      name: service
      password: Kalamaja123
  boot:
    admin:
      client:
        enabled: false
        username: admin
        password: Kalamaja123
        url: http://localhost:8081
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  sleuth:
    messaging:
      jms:
        enabled: false


security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9000/v1/me/principal
    client:
      client-id: epis-service
      client-secret: epis-service

ssl:
  trustAllHTTPSHosts: true

truststore:
  path: "test_keys/truststore.jks"

mhub:
  host: a2atest1.nasdaqcsd.com
  port: 14152
  queueManager: NCSDBXT1
  channel: TULEVAP
  peerName: "CN=a2a-test-gw, O=Nasdaq CSD, C=LV"
  inboundQueue: BMMH.TULEVAP.OUT
  outboundQueue: BMMH.TULEVAP.IN
  keyStore: ${MHUB_KEYSTORE}
  keyStorePassword: ${MHUB_KEYSTORE_PASSWORD}
  userid: ${MHUB_USERID}
  password: ${MHUB_PASSWORD}

epis:
  service:
    bic: "TULEVA20PPP"

management:
  endpoints:
    web:
      exposure:
        include: '*'
---

server.port: 5000

spring:
  profiles: production
  rabbitmq:
    host: ${MQ_HOST}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtualHost: ${MQ_USERNAME}
  boot:
    admin:
      client:
        enabled: true
        url: 'https://admin.producement.com'

security:
  oauth2:
    resource:
      user-info-uri: ${USER_INFO_URI}
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

mhub:
  host: a2a-gw1.nasdaqcsd.com
  queueManager: NCSDBXP1
  peerName: "CN=a2a-gw1.nasdaqcsd.com,OU=Domain Control Validated"
---
spring:
  profiles: cloudamqp
  rabbitmq:
    host: bear.rmq.cloudamqp.com
    username: fngujuiz
    virtualHost: fngujuiz
    password: t7IsvggidA6YisWpvCLvjZKxLHG64YGO
