server:
  port: 9005
  error.whitelabel.enabled: false
  session:
    timeout: 1800

spring:
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/tuleva-onboarding
    username: tuleva-onboarding
    password: tuleva-onboarding
    initialize: true
    continue-on-error: false
    test-on-borrow: true
    test-while-idle: true
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false

security:
  oauth2:
    resource:
      filter-order: 3
      token-info-uri: http://localhost:9000/oauth/check_token
    client:
      client-id: epis-service
      client-secret: epis-service

ssl:
  trustAllHTTPSHosts: true

truststore:
  path: "test_keys/truststore.jks"

mhub:
  host: mhub.e-register.ee
#  port: 1414
  port: 2414
  queueManager: MHUB_QMGR
  channel: TULEVA
#  peerName: "CN=Eesti V채채rtpaberikeskus AS: TULEVA,OU=Corporate Authentication,O=AS Eesti V채채rtpaberikeskus,C=EE,L=Tallinn,ST=Harjumaa"
  peerName: "CN=mhub.e-register.ee, OU=IT, O=Eesti Vaartpaberikeskus AS, C=EE, L=Tallinn, ST=Harjumaa"
  inboundQueue: MHUB.PRIVATE.TULEVA.OUT
  outboundQueue: MHUB.PRIVATE.IN
  keyStore: ${MHUB_KEYSTORE}
  keyStorePassword: ${MHUB_KEYSTORE_PASSWORD}
  trustStore: ${MHUB_KEYSTORE}
  trustStorePassword: ${MHUB_KEYSTORE_PASSWORD}

socksProxyUrl: ${SOCKS_PROXY_URL:#{null}}

---

spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    initialize: false
    tomcat:
      max-active: 5

security:
  oauth2:
    resource:
      token-info-uri: ${TOKEN_INFO_URI}
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

endpoints:
  enabled: false
  health:
    enabled: true

logging:
  rollbar:
    accessToken: ${ROLLBAR_ACCESS_TOKEN}

mhub:
  host: mhub.e-register.ee
  port: 1414
  queueManager: MHUB_QMGR
  channel: TULEVA
  peerName: "CN=mhub.e-register.ee, OU=IT, O=Eesti Vaartpaberikeskus AS, C=EE, L=Tallinn, ST=Harjumaa"