version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
  test:
    docker:
      - image: circleci/openjdk:8-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "build.gradle" }}
      - run:
          name: Run tests
          command: ./gradlew test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/epis-service.git master

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          context: heroku-deployment
          filters:
            branches:
              only: master
