server:
  port: 9000
  error:
    whitelabel.enabled: false
    include-exception: true
  servlet:
    session:
      timeout: 1800

spring:
  datasource:
    platform: POSTGRESQL
    url: jdbc:postgresql://localhost:5432/tuleva-onboarding
    username: tuleva-onboarding
    password: tuleva-onboarding
    continue-on-error: false
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write_dates_as_timestamps: false

xroad:
  instance: ee-dev
  kprEndpoint: https://zoot.ml.ee/cgi-bin/TreasuryXrdWS/services/TreasuryXrdWS
  memberClass: COM
  memberCode: 14041764
  subsystemCode: tuleva
  requestTimeout: 5000
  connectionTimeout: 3000

ssl:
  trustAllHTTPSHosts: true

digidoc:
  service:
    url: https://tsp.demo.sk.ee/

mobile-id:
  service:
    name: "Testimine"

truststore:
  path: "test_keys/truststore.jks"

mandate:
  email:
    from: "avaldused@tuleva.ee"
    to: "avaldused.test@tuleva.ee"
    bcc: "avaldused@tuleva.ee"

mhub:
  host: a2atest1.nasdaqcsd.com
  port: 14152
  queueManager: NCSDBXT1
  channel: TULEVAP
  peerName: "CN=a2a-test-gw, O=Nasdaq CSD, C=LV"
  inboundQueue: BMMH.TULEVAP.OUT
  outboundQueue: BMMH.TULEVAP.IN
  keyStore: ${MHUB_KEYSTORE}
  keyStorePassword: ${MHUB_KEYSTORE_PASSWORD}
  userid: ${MHUB_USERID}
  password: ${MHUB_PASSWORD}
